### ISSUE TITLE
Fix github workflows to run frontend checks as well

### ISSUE THREAD

**Issue by sedatbasar** [sixfeetup/scaf#281]

**Comment by sedatbasar** [comment]
__Here is reference that we used in CIPR
main.yml
```yaml
frontend-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json

    - name: Frontend test
      run:  make frontend-test
```


Makefile
```yaml
backend-test: ## Execute backend tests
ifeq ($(CI),true)
	cd backend; \
	pip install \
		-r requirements/production.txt \
		-r requirements/base.txt \
		-r requirements/tests.txt; \
	cd cipr; \
	pytest --cov=./ --cov-report html --ds=config.settings.test
else
	$(KUBECTL_EXEC_BACKEND) -c "cd cipr && pytest --cov=./ --cov-report html --ds=config.settings.test"
endif

frontend-lint-and-formatting: ## Execute frontend checks
	cd frontend; \
	npm ci; \
	npm run typecheck; \
	npm run lint-src; \
	npm run format-check; \

frontend-test: ## Execute frontend tests
	make frontend-lint-and-formatting; \
	cd frontend; \
	npm run test; \

test: backend-test frontend-test ## Run all tests
## Development Targets

backend/requirements/local.txt: compile
backend/requirements/production.txt: compile
backend/requirements/tests.txt: compile
```
