### ISSUE TITLE
CHANGEME should replaced throughout with alternative handling

### ISSUE THREAD

**Issue by daveoconnor** [sixfeetup/scaf#497]
### 🐛 Describe the bug

For example, with the scaf generated setup as it is now, `sandbox/kustomization.yaml` has the following:

```
- patch: |-
      - op: add
        path: /data/DISTRIBUTION_ID
        value: "CHANGEME"
  target:
      kind: ConfigMap
      name: app-config
```

This caused friction during setup when we didn't really particularly care about cloudfront for this project.

Instead a question about the `DISTRIBUTION_ID` value should be asked during the project setup, and the entire block not be added/commented out if none is provided. 

Look for other cases of "CHANGEME" and also resolve.

### 🌎 Environments

- [ ] Sandbox
- [ ] Staging
- [ ] Production

### 📜 Relevant log output

```shell

```
