### ISSUE TITLE
Flower starts before Celery worker is ready

### ISSUE THREAD

**Issue by abosio** [sixfeetup/scaf#89]
Currently, in the Celery k8s deployment, we start the worker, and flower like so:

```
...
      containers:
        - name: celeryworker
          image: my_awesome_sixie_project_local_django:latest
          command: ["celery", "-A", "my_awesome_sixie_project", "worker", "-E", "-l", "info"]
          envFrom:
            - configMapRef:
                name: django-config
        - name: celerybeat
          image: my_awesome_sixie_project_local_django:latest
          command: ["celery", "-A", "my_awesome_sixie_project", "beat"]
          envFrom:
            - configMapRef:
                name: django-config
        - name: flower
          image: my_awesome_sixie_project_local_django:latest
          command: ["celery", "-A", "my_awesome_sixie_project", "flower"]
          envFrom:
            - configMapRef:
                name: django-config
```

But this can result in flower starting before the worker is ready, which causes this output in the console:

```
[flower] [W 230628 18:17:46 inspector:44] Inspect method active_queues failed
[flower] [W 230628 18:17:46 inspector:44] Inspect method registered failed
[flower] [W 230628 18:17:46 inspector:44] Inspect method stats failed
[flower] [W 230628 18:17:46 inspector:44] Inspect method scheduled failed
[flower] [W 230628 18:17:46 inspector:44] Inspect method reserved failed
[flower] [W 230628 18:17:46 inspector:44] Inspect method active failed
[flower] [W 230628 18:17:47 inspector:44] Inspect method revoked failed
[flower] [W 230628 18:17:47 inspector:44] Inspect method conf failed
```

This can be solved by making a separate deployment for Flower and making its startup conditional on the celery worker being ready.
